[project]
name = "pyiceberg-test"
version = "0.1.0"
description = "Using pyiceberg with Unity Catalog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyarrow>=21.0.0",
    "pyiceberg>=0.10.0",
]
